[package]
name = "task1_phuquivo"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
task1_phuquivo = "0x0"

[dev-dependencies]

[dev-addresses]